# Site settings
title: Ioannis Gkanis
description:h
# baseurl: "" # the subpath of your site, e.g. /blog
#url: https://giannisgkanis.github.io/ioannisgkanis.github.io

# User settings
username: Ioannis Gkanis
user_description: I'm a Data Scientist from Greece, always searching for the next challenge
user_title: Data Scientist
email: yannisgkanis@gmail.com
# twitter_username: lorem_ipsum
#instagram_username: -
#facebook_username:
#linkedin_username: Ioannis Gkanis
#github_username:  Ioannis Gkanis
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

